services:
  mongodb:
    image: mongo:8.2.1
    container_name: mongodb_nbd_redis
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nbd_db
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:8.2.3
    container_name: redis_nbd
    restart: always
    ports:
      - "6379:6379"
    # volumes:
    #   - redis_data:/data

volumes:
  mongo-data:
  # redis-data:
